name: 'Amazon ECS "Deploy Task Definition" Action for GitHub Actions'
description: 'Registers an Amazon ECS task definition, and deploys it to an ECS service'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  task-definition:
    description: 'The path to the ECS task definition file to register'
    required: true
  service:
    description: 'The name of the ECS service to deploy to. The action will only register the task definition if no service is given.'
    required: false
  cluster:
    description: "The name of the ECS service's cluster.  Will default to the 'default' cluster"
    required: false
  force-new-deployment:
    description: 'Whether to force a new deployment of the service. Valid value is "true". Will default to not force a new deployment.'
    required: false
  desiredCount:
    description: 'If specified force ECS service spin up exact number of replicas'
    required: false
outputs:
  task-definition-arn:
    description: 'The ARN of the registered ECS task definition'
runs:
  using: 'node16'
  main: 'dist/index.js'
